Allow setting attribute weights per attribute set.
acquia/commerce-manager pull request #47
Opened 2018-07-10 17:14 UTC by nikunjkotecha

2018-07-10 17:14 UTC, nikunjkotecha commented
cc @sdelbosc

2018-07-11 17:16 UTC, malachy-mcconnell commented
Hi Nikunj, there are some nice ode changes here but we expect attribute weights to by synchronized from the ecommerce system and not set in Drupal. Do you agree? Is this a quick-fix until we can implement synchronisation of attribute weights (sort order)?

2018-07-11 17:22 UTC, nikunjkotecha commented
Hi @malachy-mcconnell, I checked the code around automated synchronisation of attribute weights. But that still doesn't support multiple attribute (like the old code). I updated the code around extractConfigurableOptions too in the PR and updated logic should work as is. Probably we may want to set default value in config to `attribute_weights: {  }` as not all systems would have size, otherwise everything here works.

Sortable weights is something we will need to define - reason behind that - we may not have all the attributes in taxonomy terms and it is a performance killer which we should avoid till really required in the project.

2018-09-17 09:06 UTC, miromichalicka requested changes

2018-09-17 09:06 UTC, miromichalicka commented on modules/sku/src/Plugin/AcquiaCommerce/SKUType/Configurable.php
> +    $helper = \Drupal::service('acm_sku.cart_form_helper');
Inject through DI

2018-09-17 09:06 UTC, miromichalicka commented on modules/sku/src/Plugin/AcquiaCommerce/SKUType/Configurable.php
> +      $view_builder = \Drupal::entityTypeManager()->getViewBuilder('acm_sku');
Inject through DI

2018-09-17 09:06 UTC, miromichalicka commented on modules/sku/src/Plugin/AcquiaCommerce/SKUType/Configurable.php
> +    $helper = \Drupal::service('acm_sku.cart_form_helper');
Inject through DI

2018-09-17 09:06 UTC, miromichalicka commented on modules/sku/src/Plugin/AcquiaCommerce/SKUType/Configurable.php
> +    $helper = \Drupal::service('acm_sku.cart_form_helper');
Inject through DI

2018-09-17 09:06 UTC, miromichalicka commented on modules/sku/src/Plugin/AcquiaCommerce/SKUType/Simple.php
> +    $helper = \Drupal::service('acm_sku.cart_form_helper');
Inject through DI

2018-09-17 09:06 UTC, miromichalicka commented on modules/sku/src/Plugin/AcquiaCommerce/SKUType/Configurable.php
> +    $helper = \Drupal::service('acm_sku.cart_form_helper');
Inject through DI

2018-09-17 09:20 UTC, nikunjkotecha commented on modules/sku/src/Plugin/AcquiaCommerce/SKUType/Simple.php
> +    $helper = \Drupal::service('acm_sku.cart_form_helper');
@miromichalicka I request to be done latest as part of separate ticket, I don't have a way to test this as of now as we are still on 1.0 which doesn't use dependency injection at all

cc @sdelbosc

2018-09-19 15:02 UTC, malachy-mcconnell commented
On hold. Do not merge until the requested Dependency Injection can be added.

2019-03-05 10:29 UTC, nikunjkotecha commented
fixed conflicts

2019-03-06 09:19 UTC, merged